from db import db
from datetime import datetime

class Publicacion(db.Model):
    __tablename__ = 'publicacion'
    id              = db.Column(db.Integer, primary_key=True)
    nombre          = db.Column(db.String(200), nullable=False)
    logo_filename   = db.Column(db.String(255))
    flyer_filename  = db.Column(db.String(255))
    audio_filename  = db.Column(db.String(255))
    fecha_inicio    = db.Column(db.Date, nullable=False)
    fecha_fin       = db.Column(db.Date)
    descripcion     = db.Column(db.Text)
    tipo_evento     = db.Column(db.String(50))
    rifa_url        = db.Column(db.String(500))
    rifa_url_2      = db.Column(db.String(500))
    lugar           = db.Column(db.String(200))
    punto_salida    = db.Column(db.String(200))
    hora_encuentro  = db.Column(db.String(50))
    recomendaciones = db.Column(db.Text)
    desc_caminata   = db.Column(db.Text)
    direccion       = db.Column(db.String(255))
    url_externa     = db.Column(db.String(500))
    mostrar         = db.Column(db.Text, default='[]')
    sinpe_info         = db.Column(db.String(300))
    sinpe_info_2       = db.Column(db.String(300))
    sinpe_info_3       = db.Column(db.String(300))
    sinpe_info_4       = db.Column(db.String(300))
    cuenta_info        = db.Column(db.String(400))
    cuenta_info_2      = db.Column(db.String(400))
    cuenta_info_3      = db.Column(db.String(400))
    cuenta_info_4      = db.Column(db.String(400))
    cuentas_visibles   = db.Column(db.Text, default='[]')
    colaborar_detalle  = db.Column(db.String(300), default='Apoyo Sueños de Vida')
    telefono        = db.Column(db.String(50))
    whatsapp        = db.Column(db.String(50))
    facebook        = db.Column(db.String(300))
    instagram       = db.Column(db.String(300))
    tiktok          = db.Column(db.String(300))
    youtube         = db.Column(db.String(300))
    is_active       = db.Column(db.Boolean, default=True)
    monto_recaudado = db.Column(db.Float, default=0.0)
    payment_justification = db.Column(db.Text)

class LogoConfig(db.Model):
    __tablename__ = 'logo_config'
    id = db.Column(db.Integer, primary_key=True)
    mostrar = db.Column(db.Boolean, default=True)
    enlace = db.Column(db.String(500))
    tamaño_pc = db.Column(db.Integer, default=150)
    tamaño_mobile = db.Column(db.Integer, default=120)
    posicion_left = db.Column(db.Integer, default=20)
    posicion_bottom = db.Column(db.Integer, default=100)
    nombre_archivo = db.Column(db.String(255), default='logosueños.png')
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_at      = db.Column(db.DateTime, default=datetime.utcnow)
